-- Jenius Edu - Tahap 8: Audit Log
-- Jalankan sekali di Supabase SQL Editor project Panel-Keuangan-Jenius-Edu.
create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid(),
  user_email text not null default '',
  role text not null default '',
  action text not null check (action in ('CREATE','UPDATE','DELETE','LOGIN')),
  module text not null,
  record_id text not null default '',
  detail text not null default '',
  created_at timestamptz not null default now()
);
alter table public.audit_logs enable row level security;
drop policy if exists "audit_admin_select" on public.audit_logs;
drop policy if exists "audit_authenticated_insert" on public.audit_logs;
create policy "audit_admin_select" on public.audit_logs for select to authenticated using (public.jenius_role() = 'admin');
create policy "audit_authenticated_insert" on public.audit_logs for insert to authenticated with check (auth.uid() = user_id and public.jenius_role() in ('admin','guru'));
create index if not exists audit_logs_created_at_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_user_id_idx on public.audit_logs(user_id);
