/* Admin announcements and explicit teacher publication. */
(function(){
var page=document.getElementById('parentAnnouncementsPage');
var card=document.createElement('section');card.className='announcement-workspace';
card.innerHTML='<section class="card announcement-compose"><h3>Buat pengumuman</h3><p class="announcement-caption">Sampaikan informasi kepada orang tua murid yang terhubung.</p><form id="parentAnnouncementForm"><label>Judul pengumuman<input id="parentAnnouncementTitle" maxlength="150" placeholder="Contoh: Informasi libur belajar" required></label><label>Isi pengumuman<textarea id="parentAnnouncementBody" maxlength="5000" placeholder="Tuliskan keterangan tambahan (opsional jika ada gambar)…"></textarea></label><label>Poster / brosur (opsional)<input id="parentAnnouncementImage" type="file" accept="image/jpeg,image/png"><small>JPG atau PNG, maksimal 5 MB.</small></label><img id="parentAnnouncementImagePreview" alt="Preview poster" hidden style="width:100%;max-height:260px;object-fit:contain;border-radius:10px"><div class="announcement-submit"><button class="pri" type="submit">Publikasikan pengumuman</button></div></form><p id="parentAnnouncementStatus" role="status" aria-live="polite"></p></section><section class="card announcement-history"><div class="announcement-list-head"><div><h3>Pengumuman terbit</h3><p class="announcement-caption">Hingga 30 pengumuman terbaru.</p></div><button id="parentAnnouncementRefresh" type="button">Perbarui</button></div><div id="parentAnnouncementList" tabindex="0" role="region" aria-label="Daftar pengumuman"></div></section>';

page.appendChild(card);
var previewUrl;
document.getElementById('parentAnnouncementImage').onchange=function(){
if(previewUrl)URL.revokeObjectURL(previewUrl);var file=this.files[0],preview=document.getElementById('parentAnnouncementImagePreview');preview.hidden=true;
if(!file)return;if(!['image/jpeg','image/png'].includes(file.type)||file.size>5242880){this.value='';document.getElementById('parentAnnouncementStatus').textContent='Pilih JPG atau PNG maksimal 5 MB.';return;}
previewUrl=URL.createObjectURL(file);preview.src=previewUrl;preview.hidden=false;
};
async function appendPoster(target,path){if(!path)return;var r=await window.sb.storage.from('parent-announcements').createSignedUrl(path,3600);if(r.error)return;var link=document.createElement('a');link.href=r.data.signedUrl;link.target='_blank';link.rel='noopener';var img=document.createElement('img');img.src=r.data.signedUrl;img.alt='Poster pengumuman';img.loading='lazy';img.style.cssText='display:block;width:100%;max-height:300px;object-fit:contain;margin:12px 0;border-radius:10px';link.append(img);target.append(link);}

var running=false;
async function call(name,args){var r=await window.sb.rpc(name,args);if(r.error)throw r.error;return r.data;}
async function list(){var data=await call('jenius_parent_updates');var target=document.getElementById('parentAnnouncementList');target.replaceChildren();data.announcements.forEach(function(a){var item=document.createElement('div');item.className='announcement-item';var title=document.createElement('b');title.textContent=a.title;var body=document.createElement('p');body.textContent=a.body;var remove=document.createElement('button');remove.type='button';remove.textContent='Hapus';remove.className='announcement-delete';remove.onclick=async function(){if(!confirm('Hapus pengumuman ini dari portal?'))return;remove.disabled=true;try{await call('jenius_announcement_delete',{announcement_id:a.id});if(a.image_path)await window.sb.storage.from('parent-announcements').remove([a.image_path]);await list();}catch(e){document.getElementById('parentAnnouncementStatus').textContent=e.message;remove.disabled=false;}};var meta=document.createElement('small');meta.className='announcement-date';var date=new Date(a.created_at);meta.textContent=Number.isNaN(date.getTime())?'':date.toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});var head=document.createElement('div');head.className='announcement-item-head';head.append(title,remove);item.append(head,meta,body);target.append(item);appendPoster(item,a.image_path);});if(!data.announcements.length)target.textContent='Belum ada pengumuman.';}
document.getElementById('parentAnnouncementForm').onsubmit=async function(e){e.preventDefault();if(running||currentRole!=='admin')return;if(!confirm('Publikasikan pengumuman ini kepada orang tua?'))return;running=true;var button=this.querySelector('button');button.disabled=true;var status=document.getElementById('parentAnnouncementStatus');var uploadedPath=null,published=false;try{
var file=document.getElementById('parentAnnouncementImage').files[0],body=document.getElementById('parentAnnouncementBody').value;
if(!body.trim()&&!file)throw new Error('Isi pengumuman atau pilih gambar.');
if(file){if(!['image/jpeg','image/png'].includes(file.type)||file.size>5242880)throw new Error('Pilih JPG atau PNG maksimal 5 MB.');status.textContent='Mengunggah gambar…';uploadedPath=crypto.randomUUID()+ (file.type==='image/png'?'.png':'.jpg');var upload=await window.sb.storage.from('parent-announcements').upload(uploadedPath,file,{contentType:file.type,upsert:false});if(upload.error){uploadedPath=null;throw upload.error;}
await call('jenius_announcement_create_image',{announcement_title:document.getElementById('parentAnnouncementTitle').value,announcement_body:body,announcement_image:uploadedPath});
}else{await call('jenius_announcement_create',{announcement_title:document.getElementById('parentAnnouncementTitle').value,announcement_body:body});}
published=true;this.reset();document.getElementById('parentAnnouncementImagePreview').hidden=true;if(previewUrl){URL.revokeObjectURL(previewUrl);previewUrl=null;}
status.textContent='Pengumuman dipublikasikan.';await list();}catch(error){if(uploadedPath&&!published)await window.sb.storage.from('parent-announcements').remove([uploadedPath]);status.textContent=error.message;}finally{running=false;button.disabled=false;}};
document.querySelector('[data-t="n"]').addEventListener('click',async function(){try{await list();}catch(e){document.getElementById('parentAnnouncementStatus').textContent=e.message;}});
document.getElementById('parentAnnouncementRefresh').onclick=async function(){this.disabled=true;try{await list();}catch(e){document.getElementById('parentAnnouncementStatus').textContent=e.message;}finally{this.disabled=false;}};
document.addEventListener('click',async function(e){var b=e.target.closest('[data-parent-publish],[data-parent-withdraw]');if(!b||b.disabled)return;var publish=b.hasAttribute('data-parent-publish');var id=publish?b.dataset.parentPublish:b.dataset.parentWithdraw;if(!confirm(publish?'Publikasikan pencapaian, catatan, dan rekomendasi laporan ini ke orang tua? Periksa isinya terlebih dahulu.':'Tarik laporan ini dari Portal Orang Tua?'))return;b.disabled=true;try{await call('jenius_publish_report',{target_report:id,publish:publish});alert(publish?'Laporan dipublikasikan. Perubahan berikutnya perlu dipublikasikan ulang.':'Laporan ditarik dari portal.');}catch(error){alert(error.message);}finally{b.disabled=false;}});
})();
