/* Separate auth storage keeps parent and staff sessions independent. */
(async function(){
'use strict';
const $=id=>document.getElementById(id);let client,signup=false,busy=false,recovery=new URLSearchParams(location.search).get("recovery")==="1"||new URLSearchParams(location.hash.slice(1)).get("type")==="recovery";
const message=text=>{const target=$('portalAuthDialog').open?$('authForm'):$('recovery').hidden?document.querySelector('main'):$('recovery');if($('portalAuthDialog').open)target.before($('message'));else target.prepend($('message'));$('message').textContent=text||'';};
async function run(action){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);message('Memproses...');try{await action();}catch(e){message(e.message||'Gagal memproses. Silakan coba lagi.');}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function rpc(name,args){const r=await client.rpc(name,args);if(r.error)throw new Error(r.error.message.includes('Could not find')?'Portal belum diaktifkan. Hubungi pengelola.':r.error.message);return r.data;}
function row(target,title,detail,state){const wrap=document.createElement('div');wrap.className='row';const left=document.createElement('div');left.textContent=title;const small=document.createElement('small');small.textContent=detail;left.append(small);const right=document.createElement('b');right.textContent=state;right.className=['Lunas','Hadir'].includes(state)?'paid':state==='Belum'||state==='Belum Lunas'?'unpaid':'neutral';wrap.append(left,right);target.append(wrap);}
async function load(){const {data,error}=await client.auth.getSession();if(error)throw error;const user=data.session?.user;$('portalLanding').hidden=!!user||recovery;document.querySelector('.landing-nav').hidden=!!user||recovery;if(user||recovery)$('portalAuthDialog').close();if(recovery){$('auth').hidden=true;$('account').hidden=true;$('recovery').hidden=false;if(!user){$('recoveryForm').hidden=true;message('Tautan pemulihan tidak valid atau kedaluwarsa. Kembali ke login dan minta tautan baru.');}else{$('recoveryForm').hidden=false;message('');}return;}$('recovery').hidden=true;for(const id of ['admin','link','dashboard'])$(id).hidden=true;$('auth').hidden=!!user;$('account').hidden=!user;if(!user){message('');return;}$('accountEmail').textContent=user.email||'';
if(user.app_metadata?.role==='admin'){$('admin').hidden=false;message('Kelola undangan melalui Panel Pengelola → Murid → pilih anak → Undangan Orang Tua.');return;}
if(['guru','teacher'].includes(user.app_metadata?.role)){message('Gunakan akun orang tua terpisah. Akun Guru tetap masuk melalui panel utama.');return;}
const d=await rpc('jenius_parent_dashboard');if(!d.linked){$('link').hidden=false;message('Akun Anda belum terhubung dengan murid.');return;}$('dashboard').hidden=false;$('childName').textContent=d.student.nama;$('childClass').textContent=[d.student.jenjang,d.student.kelas].filter(Boolean).join(' • ');$('payments').replaceChildren();$('attendance').replaceChildren();(d.payments||[]).forEach(p=>row($('payments'),p.bulan,new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(p.jumlah)),p.status||'Belum'));(d.attendance||[]).forEach(a=>row($('attendance'),a.tanggal,'Kehadiran murid',a.status||'-'));if(!d.payments?.length)$('payments').textContent='Belum ada catatan pembayaran.';if(!d.attendance?.length)$('attendance').textContent='Belum ada catatan kehadiran.';message('');await loadHome();await loadUpdates(d.student);}

function textBlock(target,title,body){const block=document.createElement('div');block.className='reportBlock';const h=document.createElement('h3');h.textContent=title;const p=document.createElement('p');p.textContent=body||'Belum diisi';block.append(h,p);target.append(block);}
function saveReport(student,r){const w=window.open('','_blank');if(!w){message('Izinkan jendela cetak untuk menyimpan PDF.');return;}w.document.write('<!doctype html><html lang="id"><head><title>Laporan Bulanan Jenius Edu</title><style>body{font:16px/1.6 system-ui;margin:40px;color:#17365a}p{white-space:pre-wrap}h1{font-size:26px}section{break-inside:avoid}@media print{button{display:none}}</style></head><body><h1>Jenius Edu • Laporan Bulanan</h1><main></main><button onclick="window.print()">Cetak / Simpan sebagai PDF</button></body></html>');w.document.close();const main=w.document.querySelector('main');textBlock(main,student.nama,[student.jenjang,student.kelas,r.bulan].filter(Boolean).join(' • '));textBlock(main,'Pencapaian',r.pencapaian);textBlock(main,'Catatan untuk Orang Tua',r.catatan);textBlock(main,'Latihan dan Rekomendasi',r.rekomendasi);w.focus();w.print();}
async function loadUpdates(student){for(const id of ['progress','monthlyReports','announcements'])$(id).replaceChildren();try{const u=await rpc('jenius_parent_updates');const latest=u.reports[0];$('summaryReport').textContent=latest?latest.bulan:'Belum ada';$('summaryAchievement').textContent=latest?(latest.pencapaian||'Laporan tersedia').slice(0,90):'Menunggu publikasi guru';if(latest){textBlock($('progress'),'Pencapaian • '+latest.bulan,latest.pencapaian);textBlock($('progress'),'Latihan di rumah',latest.rekomendasi);}else $('progress').textContent='Guru belum mempublikasikan perkembangan belajar.';u.reports.forEach(r=>{const card=document.createElement('article');card.className='reportBlock';textBlock(card,'Laporan • '+r.bulan,r.pencapaian);textBlock(card,'Catatan untuk Orang Tua',r.catatan);textBlock(card,'Rekomendasi',r.rekomendasi);const b=document.createElement('button');b.type='button';b.textContent='Simpan PDF';b.onclick=()=>saveReport(student,r);card.append(b);$('monthlyReports').append(card);});if(!u.reports.length)$('monthlyReports').textContent='Belum ada laporan yang dipublikasikan.';u.announcements.forEach(a=>textBlock($('announcements'),a.title,a.body));if(!u.announcements.length)$('announcements').textContent='Belum ada pengumuman.';}catch(e){for(const id of ['progress','monthlyReports','announcements'])$(id).textContent='Fitur belum tersedia. Hubungi pengelola.';message(e.message);}}

const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
async function loadHome(){for(const id of ['summaryAttendance','summaryUnpaid'])$(id).textContent='—';$('summaryBills').textContent='';$('summaryMonth').textContent='';$('receipts').replaceChildren();try{const h=await rpc('jenius_parent_home');$('summaryAttendance').textContent=h.present_count+' / '+h.attendance_total+' hadir';$('summaryMonth').textContent='Periode '+h.month;$('summaryUnpaid').textContent=money(h.unpaid_total);$('summaryBills').textContent=h.unpaid_count+' tagihan dari seluruh periode';h.receipts.forEach(p=>{const row=document.createElement('div');row.className='receipt-action';const info=document.createElement('div');info.textContent=p.bulan;const amount=document.createElement('small');amount.textContent=money(p.jumlah)+' • Lunas';info.append(amount);const b=document.createElement('button');b.type='button';b.className='secondary';b.textContent='Kuitansi / PDF';b.onclick=()=>{const w=window.open('','_blank');if(!w){message('Izinkan jendela baru untuk kuitansi.');return;}w.document.write('<!doctype html><html lang="id"><head><title>Kuitansi Jenius Edu</title><style>body{font:16px/1.6 system-ui;margin:40px;color:#17365a}p{white-space:pre-wrap}@media print{button{display:none}}</style></head><body><h1>Jenius Edu • Kuitansi Pembayaran</h1><main><p>Memuat kuitansi...</p></main></body></html>');w.document.close();run(async()=>{try{const receipt=await rpc('jenius_parent_receipt',{target_payment:p.id});const target=w.document.querySelector('main');target.replaceChildren();textBlock(target,'Nama murid',receipt.nama);textBlock(target,'Periode',receipt.bulan);textBlock(target,'Jumlah dibayar',money(receipt.jumlah));textBlock(target,'Status',receipt.status);textBlock(target,'Tanggal pembayaran',receipt.tanggal_bayar||'Belum dicatat');textBlock(target,'Metode pembayaran',receipt.metode||'Belum dicatat');if(receipt.invoice?.nomor)textBlock(target,'Nomor invoice',receipt.invoice.nomor);textBlock(target,'Referensi pembayaran',receipt.payment_id);const print=w.document.createElement('button');print.textContent='Cetak / Simpan sebagai PDF';print.onclick=()=>w.print();target.append(print);w.focus();w.print();message('Kuitansi siap. Pilih Simpan sebagai PDF di jendela cetak.');}catch(e){if(!w.closed)w.document.querySelector('main').textContent=e.message;throw e;}});};row.append(info,b);$('receipts').append(row);});if(!h.receipts.length)$('receipts').textContent='Belum ada pembayaran lunas.';}catch(e){$('receipts').textContent='Kuitansi belum tersedia. Hubungi pengelola.';message(e.message);}}
$('forgot').onclick=()=>run(async()=>{if(!$('email').reportValidity())return;const email=$('email').value.trim();if(!email)throw new Error('Isi alamat email Anda terlebih dahulu.');const r=await client.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/orang-tua.html?recovery=1'});if(r.error)throw r.error;message('Jika email terdaftar, tautan pemulihan akan dikirim. Periksa inbox dan folder spam.');});
$('recoveryForm').onsubmit=e=>{e.preventDefault();run(async()=>{const password=$('newPassword').value;if(password!==$('confirmPassword').value)throw new Error('Kedua password belum sama.');const r=await client.auth.updateUser({password});if(r.error)throw r.error;await client.auth.signOut();recovery=false;$('newPassword').value='';$('confirmPassword').value='';history.replaceState(null,'',location.pathname);await load();message('Password berhasil diperbarui. Silakan login dengan password baru.');});};
$('cancelRecovery').onclick=()=>run(async()=>{await client.auth.signOut();recovery=false;history.replaceState(null,'',location.pathname);await load();});
document.querySelectorAll('[data-portal-mode]').forEach(b=>{b.onclick=()=>{const wantSignup=b.dataset.portalMode==='signup';if(signup!==wantSignup)$('mode').click();$('auth').hidden=false;$('portalAuthDialog').showModal();message('');$('email').focus();};});$('closePortalAuth').onclick=()=>{$('portalAuthDialog').close();message('');};
$('passwordToggle').onclick=()=>{const show=$('password').type==='password';$('password').type=show?'text':'password';$('passwordToggle').textContent=show?'Sembunyikan':'Lihat';$('passwordToggle').setAttribute('aria-label',show?'Sembunyikan password':'Tampilkan password');$('passwordToggle').setAttribute('aria-pressed',String(show));};
$('mode').onclick=()=>{signup=!signup;$('forgot').hidden=signup;$('authHint').textContent=signup?'Daftar dengan email Anda, lalu hubungkan menggunakan kode undangan.':'Masuk untuk melihat informasi anak Anda.';$('password').placeholder=signup?'Buat password minimal 8 karakter':'Masukkan password';$('authTitle').textContent=signup?'Buat akun orang tua':'Selamat datang kembali';$('submit').textContent=signup?'Daftar akun':'Masuk ke Portal';$('password').autocomplete=signup?'new-password':'current-password';$('mode').textContent=signup?'Sudah punya akun? Masuk':'Buat akun orang tua';message('');};
$('authForm').onsubmit=e=>{e.preventDefault();run(async()=>{const credentials={email:$('email').value.trim(),password:$('password').value};const r=signup?await client.auth.signUp({...credentials,options:{emailRedirectTo:location.origin+'/orang-tua.html'}}):await client.auth.signInWithPassword(credentials);if(r.error)throw r.error;$('password').value='';if(signup&&!r.data.session){message('Pendaftaran diterima. Periksa email untuk konfirmasi, lalu kembali ke portal dan login.');return;}await load();});};
$('logout').onclick=()=>run(async()=>{const r=await client.auth.signOut();if(r.error)throw r.error;await load();});
$('claimForm').onsubmit=e=>{e.preventDefault();run(async()=>{await rpc('jenius_parent_claim',{invitation_code:$('code').value.trim()});$('code').value='';await load();});};
$('refresh').onclick=()=>run(load);
try{const response=await fetch('/api/config',{cache:'no-store'});if(!response.ok)throw new Error('Konfigurasi belum tersedia.');const cfg=await response.json();if(!cfg.url||!cfg.key||!window.supabase)throw new Error('Portal belum siap. Muat ulang atau hubungi pengelola.');client=window.supabase.createClient(cfg.url,cfg.key,{auth:{storageKey:'jenius-parent-auth'}});client.auth.onAuthStateChange((event)=>{if(event==='PASSWORD_RECOVERY'){recovery=true;setTimeout(()=>{if(!busy)run(load);},0);}});await load();}catch(e){message(e.message);document.querySelectorAll('button').forEach(b=>b.disabled=true);}
})();
