/* Admin announcements and explicit teacher publication. */
(function(){
var page=document.getElementById('studentProfilePage');
var card=document.createElement('section');card.className='card';
card.innerHTML='<h3>Pengumuman untuk Orang Tua</h3><p>Pengumuman ini terlihat oleh semua akun orang tua yang terhubung.</p><form id="parentAnnouncementForm"><label>Judul<input id="parentAnnouncementTitle" maxlength="150" required></label><label>Isi<textarea id="parentAnnouncementBody" maxlength="5000" required style="width:100%;min-height:100px"></textarea></label><button type="submit">Publikasikan pengumuman</button></form><p id="parentAnnouncementStatus" role="status"></p><button id="parentAnnouncementRefresh" type="button">Lihat pengumuman</button><div id="parentAnnouncementList"></div>';
page.appendChild(card);
var running=false;
async function call(name,args){var r=await window.sb.rpc(name,args);if(r.error)throw r.error;return r.data;}
async function list(){var data=await call('jenius_parent_updates');var target=document.getElementById('parentAnnouncementList');target.replaceChildren();data.announcements.forEach(function(a){var item=document.createElement('div');item.className='profile-text-row';var title=document.createElement('b');title.textContent=a.title;var body=document.createElement('p');body.textContent=a.body;var remove=document.createElement('button');remove.type='button';remove.textContent='Hapus pengumuman';remove.onclick=async function(){if(!confirm('Hapus pengumuman ini dari portal?'))return;remove.disabled=true;try{await call('jenius_announcement_delete',{announcement_id:a.id});await list();}catch(e){document.getElementById('parentAnnouncementStatus').textContent=e.message;remove.disabled=false;}};item.append(title,body,remove);target.append(item);});if(!data.announcements.length)target.textContent='Belum ada pengumuman.';}
document.getElementById('parentAnnouncementForm').onsubmit=async function(e){e.preventDefault();if(running||currentRole!=='admin')return;if(!confirm('Publikasikan pengumuman ini kepada orang tua?'))return;running=true;var button=this.querySelector('button');button.disabled=true;var status=document.getElementById('parentAnnouncementStatus');try{await call('jenius_announcement_create',{announcement_title:document.getElementById('parentAnnouncementTitle').value,announcement_body:document.getElementById('parentAnnouncementBody').value});this.reset();status.textContent='Pengumuman dipublikasikan.';await list();}catch(error){status.textContent=error.message;}finally{running=false;button.disabled=false;}};
document.getElementById('parentAnnouncementRefresh').onclick=async function(){this.disabled=true;try{await list();}catch(e){document.getElementById('parentAnnouncementStatus').textContent=e.message;}finally{this.disabled=false;}};
document.addEventListener('click',async function(e){var b=e.target.closest('[data-parent-publish],[data-parent-withdraw]');if(!b||b.disabled)return;var publish=b.hasAttribute('data-parent-publish');var id=publish?b.dataset.parentPublish:b.dataset.parentWithdraw;if(!confirm(publish?'Publikasikan pencapaian, catatan, dan rekomendasi laporan ini ke orang tua? Periksa isinya terlebih dahulu.':'Tarik laporan ini dari Portal Orang Tua?'))return;b.disabled=true;try{await call('jenius_publish_report',{target_report:id,publish:publish});alert(publish?'Laporan dipublikasikan. Perubahan berikutnya perlu dipublikasikan ulang.':'Laporan ditarik dari portal.');}catch(error){alert(error.message);}finally{b.disabled=false;}});
})();
