/* Separate auth storage keeps parent and staff sessions independent. */
(async function(){
'use strict';
const $=id=>document.getElementById(id);let client,signup=false,busy=false;
const message=text=>{$('message').textContent=text||'';};
async function run(action){if(busy)return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);message('Memproses...');try{await action();}catch(e){message(e.message||'Gagal memproses. Silakan coba lagi.');}finally{busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);}}
async function rpc(name,args){const r=await client.rpc(name,args);if(r.error)throw new Error(r.error.message.includes('Could not find')?'Portal belum diaktifkan. Hubungi pengelola.':r.error.message);return r.data;}
function row(target,title,detail,state){const wrap=document.createElement('div');wrap.className='row';const left=document.createElement('div');left.textContent=title;const small=document.createElement('small');small.textContent=detail;left.append(small);const right=document.createElement('b');right.textContent=state;right.className=state==='Lunas'?'paid':'unpaid';wrap.append(left,right);target.append(wrap);}
async function load(){const {data,error}=await client.auth.getSession();if(error)throw error;const user=data.session?.user;for(const id of ['admin','link','dashboard'])$(id).hidden=true;$('auth').hidden=!!user;$('account').hidden=!user;if(!user){message('');return;}$('accountEmail').textContent=user.email||'';
if(user.app_metadata?.role==='admin'){$('admin').hidden=false;const r=await client.from('students').select('id,nama,kelas').order('nama');if(r.error)throw r.error;$('student').replaceChildren();(r.data||[]).forEach(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=s.nama+' • '+(s.kelas||'kelas belum diisi');$('student').append(o);});const matches=(r.data||[]).filter(s=>s.nama.trim().toLowerCase()==='lita');if(matches.length===1)$('student').value=matches[0].id;message(matches.length===1?'Pilih Buat kode undangan untuk Lita.':'Periksa dan pilih data Lita yang benar sebelum membuat undangan.');return;}
if(['guru','teacher'].includes(user.app_metadata?.role)){message('Gunakan akun orang tua terpisah. Akun Guru tetap masuk melalui panel utama.');return;}
const d=await rpc('jenius_parent_dashboard');if(!d.linked){$('link').hidden=false;message('Akun Anda belum terhubung dengan murid.');return;}$('dashboard').hidden=false;$('childName').textContent=d.student.nama;$('childClass').textContent=[d.student.jenjang,d.student.kelas].filter(Boolean).join(' • ');$('payments').replaceChildren();$('attendance').replaceChildren();(d.payments||[]).forEach(p=>row($('payments'),p.bulan,new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(p.jumlah)),p.status||'Belum'));(d.attendance||[]).forEach(a=>row($('attendance'),a.tanggal,'Kehadiran murid',a.status||'-'));if(!d.payments?.length)$('payments').textContent='Belum ada catatan pembayaran.';if(!d.attendance?.length)$('attendance').textContent='Belum ada catatan kehadiran.';message('');}
$('mode').onclick=()=>{signup=!signup;$('authTitle').textContent=signup?'Daftar akun orang tua':'Masuk ke portal';$('submit').textContent=signup?'Daftar':'Masuk';$('password').autocomplete=signup?'new-password':'current-password';$('mode').textContent=signup?'Sudah punya akun? Masuk':'Belum punya akun? Daftar';message('');};
$('authForm').onsubmit=e=>{e.preventDefault();run(async()=>{const credentials={email:$('email').value.trim(),password:$('password').value};const r=signup?await client.auth.signUp({...credentials,options:{emailRedirectTo:location.origin+'/orang-tua.html'}}):await client.auth.signInWithPassword(credentials);if(r.error)throw r.error;$('password').value='';if(signup&&!r.data.session){message('Pendaftaran diterima. Periksa email untuk konfirmasi, lalu kembali ke portal dan login.');return;}await load();});};
$('logout').onclick=()=>run(async()=>{const r=await client.auth.signOut();if(r.error)throw r.error;await load();});
$('claimForm').onsubmit=e=>{e.preventDefault();run(async()=>{await rpc('jenius_parent_claim',{invitation_code:$('code').value.trim()});$('code').value='';await load();});};
$('generate').onclick=()=>run(async()=>{if(!$('student').value)throw new Error('Pilih murid terlebih dahulu.');if(!confirm('Buat undangan untuk '+$('student').selectedOptions[0].textContent+'? Uji coba hanya mengaktifkan murid ini.')){message('');return;}const r=await rpc('jenius_parent_invite',{target_student:$('student').value});$('inviteCode').value=r.code;$('invitation').hidden=false;message('Undangan untuk '+r.nama+' berhasil dibuat. Kode sebelumnya yang belum dipakai dinonaktifkan.');});
$('copy').onclick=()=>run(async()=>{await navigator.clipboard.writeText($('inviteCode').value);message('Kode undangan disalin.');});$('refresh').onclick=()=>run(load);
try{const response=await fetch('/api/config',{cache:'no-store'});if(!response.ok)throw new Error('Konfigurasi belum tersedia.');const cfg=await response.json();if(!cfg.url||!cfg.key||!window.supabase)throw new Error('Portal belum siap. Muat ulang atau hubungi pengelola.');client=window.supabase.createClient(cfg.url,cfg.key,{auth:{storageKey:'jenius-parent-auth'}});await load();}catch(e){message(e.message);document.querySelectorAll('button').forEach(b=>b.disabled=true);}
})();
