const assert=require('node:assert/strict'),fs=require('node:fs');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
(async()=>{const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('test.uid',true),'')::uuid $$;
create function public.jenius_role() returns text language sql as $$ select current_setting('test.role',true) $$;
create table students(id uuid primary key,nama text,jenjang text,kelas text,hp text);
create table payments(id uuid primary key,student_id uuid references students(id),bulan text,jumlah numeric,status text);
create table teacher_attendance(id uuid primary key,student_id uuid references students(id),tanggal date,status text,catatan text);
insert into auth.users values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'),('cccccccc-cccc-cccc-cccc-cccccccccccc');
insert into students values('11111111-1111-1111-1111-111111111111','Lita','SD','2','PRIVATE'),('22222222-2222-2222-2222-222222222222','Other','SD','3','SECRET');
insert into payments values(gen_random_uuid(),'11111111-1111-1111-1111-111111111111','2026-10',200000,'Belum'),(gen_random_uuid(),'22222222-2222-2222-2222-222222222222','2026-10',500000,'Lunas');
insert into teacher_attendance values(gen_random_uuid(),'11111111-1111-1111-1111-111111111111','2026-10-08','Hadir','INTERNAL');`);
const sql=fs.readFileSync('supabase/parent_portal.sql','utf8');await db.exec(sql);await db.exec(sql);
const rpc=async(name,args=[]) => (await db.query(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')}) result`,args)).rows[0].result;
await db.exec(`set role authenticated;set test.uid='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';set test.role='admin';`);
const invite=await rpc('jenius_parent_invite',['11111111-1111-1111-1111-111111111111']);assert.equal(invite.code.length,32);
await assert.rejects(()=>rpc('jenius_parent_invite',['22222222-2222-2222-2222-222222222222']),/satu murid/);
await db.exec(`set test.uid='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';set test.role='';`);
assert.equal((await rpc('jenius_parent_dashboard')).linked,false);
await assert.rejects(()=>rpc('jenius_parent_invite',['11111111-1111-1111-1111-111111111111']),/Hanya Admin/);
await assert.rejects(()=>db.query('select * from public.parent_links'),/permission denied/);
await assert.rejects(()=>rpc('jenius_parent_claim',['00000000000000000000000000000000']),/tidak valid/);
await rpc('jenius_parent_claim',[invite.code]);const dashboard=await rpc('jenius_parent_dashboard');assert.equal(dashboard.student.nama,'Lita');assert.equal(dashboard.payments.length,1);assert.equal(dashboard.attendance.length,1);assert.equal(JSON.stringify(dashboard).includes('PRIVATE'),false);assert.equal(JSON.stringify(dashboard).includes('INTERNAL'),false);assert.equal(JSON.stringify(dashboard).includes('Other'),false);
await db.exec(`set test.uid='cccccccc-cccc-cccc-cccc-cccccccccccc';`);assert.equal((await rpc('jenius_parent_dashboard')).linked,false);await assert.rejects(()=>rpc('jenius_parent_claim',[invite.code]),/tidak valid/);
await db.exec(`set test.uid='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';set test.role='admin';`);
const old=await rpc('jenius_parent_invite',['11111111-1111-1111-1111-111111111111']);const next=await rpc('jenius_parent_invite',['11111111-1111-1111-1111-111111111111']);
await db.exec(`set test.uid='cccccccc-cccc-cccc-cccc-cccccccccccc';set test.role='';`);await assert.rejects(()=>rpc('jenius_parent_claim',[old.code]),/tidak valid/);
await db.exec(`reset role;update parent_invites set expires_at=now()-interval '1 second' where used_by is null;set role authenticated;`);await assert.rejects(()=>rpc('jenius_parent_claim',[next.code]),/tidak valid/);
await db.exec(`set test.uid='';`);await assert.rejects(()=>rpc('jenius_parent_dashboard'),/login/);
await db.exec(`reset role;drop table teacher_attendance;set role authenticated;set test.uid='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';`);assert.deepEqual((await rpc('jenius_parent_dashboard')).attendance,[]);

await db.exec(`reset role;create table teacher_reports(id uuid primary key,student_id uuid references students(id),teacher_id uuid references auth.users(id),bulan text,pencapaian text,catatan text,rekomendasi text);
insert into teacher_reports values('33333333-3333-3333-3333-333333333333','11111111-1111-1111-1111-111111111111','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','2026-10','Bisa membaca','PUBLIC NOTE','Latihan membaca');`);
const updates=fs.readFileSync('supabase/parent_updates.sql','utf8');await db.exec(updates);await db.exec(updates);
await db.exec(`set role authenticated;set test.uid='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';set test.role='';`);
assert.equal((await rpc('jenius_parent_updates')).reports.length,0);
await assert.rejects(()=>rpc('jenius_publish_report',['33333333-3333-3333-3333-333333333333',true]),/Akses ditolak/);
await assert.rejects(()=>rpc('jenius_announcement_create',['Title','Body']),/Hanya Admin/);
await db.exec(`set test.uid='cccccccc-cccc-cccc-cccc-cccccccccccc';set test.role='guru';`);
await assert.rejects(()=>rpc('jenius_publish_report',['33333333-3333-3333-3333-333333333333',true]),/bukan milik/);
await db.exec(`set test.uid='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';set test.role='guru';`);await rpc('jenius_publish_report',['33333333-3333-3333-3333-333333333333',true]);
await db.exec(`reset role;update teacher_reports set pencapaian='PRIVATE EDIT';set role authenticated;set test.uid='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';set test.role='';`);
assert.equal((await rpc('jenius_parent_updates')).reports[0].pencapaian,'Bisa membaca');
await assert.rejects(()=>db.query('select * from parent_report_publications'),/permission denied/);
await db.exec(`set test.uid='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';set test.role='admin';`);const aid=await rpc('jenius_announcement_create',['Libur','Besok libur']);
await db.exec(`set test.uid='cccccccc-cccc-cccc-cccc-cccccccccccc';set test.role='';`);assert.equal((await rpc('jenius_parent_updates')).announcements.length,0);
await db.exec(`set test.uid='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';`);assert.equal((await rpc('jenius_parent_updates')).announcements.length,1);
await db.exec(`set test.uid='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';set test.role='admin';`);await rpc('jenius_publish_report',['33333333-3333-3333-3333-333333333333',false]);await rpc('jenius_announcement_delete',[aid]);
await db.exec(`set test.uid='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb';set test.role='';`);assert.equal((await rpc('jenius_parent_updates')).reports.length,0);assert.equal((await rpc('jenius_parent_updates')).announcements.length,0);
console.log('PASS: report ownership, explicit publication, immutable snapshot after private edits, withdrawal, admin announcements, linked-only access, private tables.');
console.log('PASS: migration rerun, single-child pilot, admin-only invite, private tables, linked-only dashboard, no private fields, one-use/revoked/expired codes, anonymous denial, optional attendance.');await db.close();})().catch(e=>{console.error(e);process.exit(1);});
